### PR TITLE
Add show_only_folders property

### PR DESCRIPTION
**Pull request by andriykorchak**
Hi @crahan 

I've added `show_only_folders` property to `FileChooser` class.

It may be useful in cases when the user is asked to select a folder (ie output folder for saving multiple generated files).

Please let me know if you have any comments.

Thanks.

Andrii

### CODE REVIEW

**Comment by crahan** [comment]
Thank you for your contribution!

The PR looks good. I'm wondering about the risk of overwriting files that already exist but which are hidden from sight when using this option though. Currently the widget allows for selecting a folder by navigating into it and leaving the filename blank. Is that option too cluttered? Do you consider not showing the files that might be overwritten as an issue (not giving the user a visual cue that a folder they navigated into does have files inside it)?

There's also the risk of users still entering a filename which might make things confusing. The easiest solution would be to disable the filename input field when the file dialog is created or disable and clear the field when the flag is set on an existing file dialog. I would need to think about that option a little more though.

**Comment by andriykorchak** [comment]
Thanks for a quick response.

On the project I'm working on overwriting existing files is the intended behavior. For other use cases we can highlight selected folder with a different color (as it's currently done for files). Let me know if you like this idea.

I think leaving filename blank is ok when the user just wants to select existing folder.

When they do type something in that field I would interpret that as a need to create a new folder.

**Comment by andriykorchak** [comment]
Hi @crahan 

I went ahead and added highlighting existing folder selection.

Let me know if you think other changes are needed.

**Comment by crahan** [comment]
The option to enter a folder name and have it highlighted (to indicate a folder already exists) would cause confusion if there's already a file with the same name (which would not be visible if only folders are being shown). I'll need some time to review, but at this point I'm leaning more towards implementing the folder-only option in such a way that the text input field for entering a file name is disabled or removed completely when only folders need to be shown.

**Comment by andriykorchak** [comment]
I still think that having that field enabled may be useful in some cases (ie giving the user option to select a name for a new folder). But I agree that the case you described (user entered folder name = existing file name) can cause confusion.

One possible solution would be to highlight such case (user entered folder name that matches existing file name) with a different color (ie 'red').

Another solution - do not allow to close the dialog until a 'proper' folder is selected (the one with the name that doesn't match any existing files).

But if you insist on having that field disabled completely - that's ok. Let me know - I can implement either option. Thanks.

**Comment by crahan** [comment]
To not complicate things unnecessarily I'd prefer the option to disable the input field when folder-only mode is selected. In that case the dialog becomes a folder chooser.

**Comment by andriykorchak** [comment]
Sounds good, thanks.

I just disabled this field for show_only_folders mode. Let me know if you have any other feedback.

**Comment by crahan** [comment]
Thanks for the updates. I'll review and try and get this merged asap.

**Comment by andriykorchak** [comment]
I just wanted it to be more consistent with file selection version. I can remove it if you think it's cleaner that way.

**Comment by crahan** [comment]
Ok let's leave it in for now and I'll try and review asap. Thanks for the help!

**Comment by crahan** [comment]
I've merged this into a new dev branch to track improvements before the next release. Thanks for the contribution!

**Comment by crahan** [comment]
@andriykorchak would you mind testing the current version in the `dev` branch? I've added some functionality in addition to your changes for the folder-only mode:

1. moving between folder-only and standard mode now hides/shows the filename field (and expands the path selector accordingly)
2. going to folder-only mode resets the dialog (i.e. unsets any selected values) and zeros out the filename value
3. going to standard mode resets the dialog (i.e. unsets any selected values) and sets the filename to the default value

I've run some initial tests and everything appears to work as expected.

**Comment by andriykorchak** [comment]
Sure, will do.

**Comment by andriykorchak** [comment]
@crahan I've tested dev branch and everything works for me.

Unrelated question: I was planning to implement a suggestion from #12 (filter file names). Should I create a pull request to dev branch or it's better to still use master?

Thanks.

**Comment by crahan** [comment]
Dev is probably best, thanks!

**Pull request merged**
